# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

norm_drl_rcpp <- function(alpha, y_mat, y, w_mat, e_mat) {
    .Call(`_causalDML_norm_drl_rcpp`, alpha, y_mat, y, w_mat, e_mat)
}

